package Day24;

/*
 * Question 389 - Find the Difference
 * 
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t. 

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 */
import java.util.Arrays;

public class Q1 {
    public char findTheDifference(String s, String t) {
        var charS = s.toCharArray();
        var charT = t.toCharArray();
        char a = ' ';

        Arrays.sort(charS);
        Arrays.sort(charT);        

        for(int i=0; i<charS.length; i++){
            if(charS[i] != charT[i]){
                return charT[i];
            }
        }

        if(charS.length != charT.length){
            return charT[charT.length - 1];
        }
        return a;
    }
}
